### PR TITLE
support gradle

### PR DESCRIPTION
**Pull request by googolmo**

### CODE REVIEW

**Comment by Wavesonics** [comment]
Additionally, with Gradle support, getting an aar in Maven central would be awesome.

**Comment by mpost** [comment]
@Wavesonics Absolutly!

**Comment by adek** [comment]
I hope Jake will read this and give us official gradle support. I'm also using it in my project and it's the only project I can't use from gradle.

I found that someone already did that: https://bintray.com/populov/maven/com.viewpagerindicator:library/release
but official release from Jake would be very helpful.

**Comment by johnhamelink** [comment]
Gradle looks like it's going to be the future for android development, lets get support for it in the master branch please!

**Comment by stefanomunarini** [comment]
+1. Cause Android Studio now just let you import gradle project/lib.

**Comment by kikoso** [comment]
+1

**Comment by coyarzun89** [comment]
+1

**Comment by joluet** [comment]
+1

**Comment by ArthurSav** [comment]
Yes, gradle support would be great

**Comment by mediavrog** [comment]
+1

**Comment by cesar-lima1** [comment]
+1

**Comment by gandharva** [comment]
+1

**Comment by mpost** [comment]
You should all migrate to the pagestripindicator from a stuetz.
Am 13.02.2014 12:11 schrieb "gandharva kumar" notifications@github.com:

**Comment by gandharva** [comment]
any link? Can't find it

**Comment by mpost** [comment]
https://github.com/astuetz/PagerSlidingTabStrip
Am 13.02.2014 12:15 schrieb "gandharva kumar" notifications@github.com:

**Comment by intrications** [comment]
@mpost PagerSlidingTabStrip is useful in some cases but it offers completely different functionality to this library.

**Comment by mpost** [comment]
Completely?
Am 13.02.2014 20:05 schrieb "Michael Basil" notifications@github.com:

**Pull request closed without merging**
