### PR TITLE
Added samples for Multi-line Tab Indicators; and Dynamically changing Tab Indicators.

### PR DESCRIPTION
**Pull request by curioustechizen**
Added the following samples:
1. Displaying Tab Indicators in multiple lines.
2. Updating the Tab Indicators dynamically, without user intervention.

### CODE REVIEW

**Comment by SimonVT** [comment]
Pull request needs to be re-made against dev,

**Comment by curioustechizen** [comment]
@SimonVT Thanks for the corrections. This is the first time I've made a pull request and I guess the spacing and other problems might have been because I copy-pasted code into the online GitHub Editor from my Eclipse IDE.

**Comment by curioustechizen** [comment]
@SimonVT Do I need to make my edits on the dev branch of my fork and then make a pull request against dev branch of the original? (Pardon my ignorance, I'm relatively new to git and github).

**Comment by SimonVT** [comment]
There might be merge conflicts if you don't, but you could try just merging your master into dev. Safest is always to have your changes on the dev branch tho.

**Comment by curioustechizen** [comment]
Re-issuing a pull request against dev branch. Closing this one.

**Comment by curioustechizen** [comment]
@SimonVT , based on your suggestion, I closed this pull request and opened another one against the dev branch ( #177 ) - However, I see that the travis build on the new pull request fails. I do not understand the failures in the travis build log. Is there anything I need to do to fix this?

**Pull request closed without merging**
