### PR TITLE
Added Gradle Build Files

### PR DESCRIPTION
**Pull request by alex-richards**

### CODE REVIEW

**Comment by philippeluickx** [comment]
+1

**Comment by kierans** [comment]
+1

**Comment by hwrdprkns** [comment]
+1 should probably upload to maven also

**Comment by ralphilius** [comment]
+1

Merge to [android-orphanage/ViewPagerIndicator](https://github.com/android-orphanage/ViewPagerIndicator)

**Review by THEWOLF666 — APPROVED** [review]

**Pull request closed without merging**
