### PR TITLE
IconPageIndicator

### PR DESCRIPTION
**Pull request by jmrboosties**
Added support for IconPageIndicator class. Built based on the TitlePageIndicator class.

FEATURES:
- Allows users to set icons for their views which will be displayed based on that view's relative position in the View Pager
- Users can control footer color, size, padding similar to TitlePageIndicator
- Users can control icon padding, position, and the opacity of the side icons (the centered icon fades when sliding left or right).
- Included IconProvider interface for users to declare which drawables to use as icons.
- Updated README to include documentation on new class (You will probably want to rearrange it a bit, I set the README to feature my changes more prominently in my fork).

POTENTIAL CHANGES
- We could create a hybrid class which supports both titles and icons, for instance, arrow icons to the left and right but the title as text when a view is in focus (centered).
- Create a styleable super class which both title and icon page indicators extend to avoid naming issues (admittedly not too experience with this).

### CODE REVIEW

**Comment by micHar** [comment]
"We could create a hybrid class which supports both titles and icons, for instance, arrow icons to the left and right but the title as text when a view is in focus (centered)."

Now this one would be great! It's what I'm looking for, I'm not sure if I'm experienced enough to contribute, though...

**Comment by jmrboosties** [comment]
I had initially planned something like that. I don't know if it would be worth making a separate class, or just having the style as a property. Any thoughts?

**Comment by ChristopheVersieux** [comment]
Seems awesome!
Great work, I just discovered that work and will try it ASAP!

**Comment by JakeWharton** [comment]
This is not the route I am planning to take this type of feature. I have something a bit different in mind moving forward. Thanks for submitting!

**Pull request closed without merging**
