### PR TITLE
Fix poor quality selected title (selected title has been drawn twice)

### PR DESCRIPTION
**Pull request by protyposis**

### CODE REVIEW

**Comment by rfgamaral** [comment]
Have you tested this?

I didn't test your exact version but I remember having tested the same solution and it didn't work in the sense that when moving pages around, the title would start to fade until it's completely transparent and that shouldn't happen.

Doesn't this happen to you?

**Comment by protyposis** [comment]
Oh damn you're right. I tested it but didn't notice that it disappears... I'll try to fix it.

**Comment by protyposis** [comment]
Problem resolved, title doesn't fade out any longer.

**Comment by JakeWharton** [comment]
Merged into `dev`

**Pull request closed without merging**
